name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js for backend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install backend dependencies
      working-directory: ./backend
      run: npm install

    - name: Run backend tests
      working-directory: ./backend
      run: npm test

    - name: Set up Node.js for frontend
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm install

    - name: Ensure public/index.html exists
      run: ls ./frontend/public/index.html
      working-directory: ./frontend

    - name: Run frontend build
      working-directory: ./frontend
      run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Deploy to Staging
      run: echo "Deploying to Staging"
